### ISSUE TITLE
s04e08 心智文采

### ISSUE THREAD

**Issue by liaodapo** [GC4WP/GC4grace42#12]
## 作业 

以小组为单位写一篇反映心智文采的英文文章，不少于500 words，可以借助课堂所讲的AI协助完成。

同时小组中作者之外的成员，将其翻译成文笔较好的中文。

**Comment by liaodapo** [comment]
屎稿用ai修改过程演示 

链接: https://pan.baidu.com/s/1wJbQ_9J3stzfg3pxIDCMvg 提取码: 6ffw

**Comment by liaodapo** [comment]
大妈的[作业](https://github.com/GC4WP/GC4grace42/blob/master/s04e08_dama.md)

**Comment by liaodapo** [comment]
В Китае 10 известных ученых: Цянь Сюэсэнь, Дэн Цзясянь, Хуа Луогенг и так далее.  Большинство из этих ученых работают над передовыми технологиями.  Но один из них изучает еду.  Это Юань Лунпин, известный как «отец гибридного риса».

 Его исследования в основном отвечают за оптимизацию сортов риса с целью усиления функции и урожайности риса.  Например, сделать рис более питательным и крепким.

 Пока его исследования даже утроили производство риса.

 Как вы можете себе представить, изначально поры давали не более 3 волосков, но теперь все поры дают более 9 волосков.  А в некоторых крайних случаях урожай риса даже вырос в 16 раз, то есть 48 волосков на пору.  Слава Китайскому Богу, в 2018 году он начал выращивать рис в пустыне Дубаи, и он уже достиг результатов.

                                  ——риопл

 **Вы видите это, как я видел английские😢*

**Comment by Karina-Han** [comment]
下面这篇，是我最近最有诚意的文章，至少花了一天时间，虽然不怎么地，do my best。
是小型的评论文章，瞎写，不是什么正式交的essay, .

--------------------------------------------------------------------------------------------------------------
**Applying postcolonial theory to social media studies: the case of racism against Asians in COVID-19 pandemic**

The postcolonial reveals the fact that western people usually view the behaviors of people in other regions from their cultural perspective. Such western-centric ideas bring misery to non-western peoples. For example, at one time, the western countries had forced Muslim women to remove their Hijab as a form of women liberation. In the culture of the west, people show their faces and make eye contact with others for communicating politely. Therefore, the west-centric logic views veils as a kind of chain that would constrain the natural human rights and freedom of women. However, in Muslim society, the Hijab is a symbol of class status, and it can protect privacy. Many Muslim women had suffered psychological trauma as a result of the campaign to ban the veil. (Young 2001)

Nowadays, a similar story appears again. During the outbreak of COVID-19, many Asians wear masks when they go shopping or other places. Since they, especially Chinese, have learned the protection knowledge from their original countries, which suggest ordinary people wear face masks to prevent infection. The ethnic Asians thought that wearing masks contribute to prevention. However, it may be considered silly that healthy people wear masks just for protection.(Jingnan, Aubrey et al. 2020) This attitude turned into actual harm, and many Asians post their experience of suffering discrimination from westerners, in the countries where they migrated, on social media.(Leung 2020) Westerners' lack of understanding of Asian culture has again caused the suffering of the disadvantaged and showed its intolerance of the different.

Besides, when President trump of the United States called the virus "Chinese virus" on twitter. The world health organization (who) has banned using the name of countries to name an infection, and it is inappropriate for a leader to make such a discriminatory statement. (Rogers, Jakes et al. 2020)His comments encouraged racist violence against Chinese Americans ethnic, and Chinese scattered across the globe suffered more severe incidents of racially motivated violence. Moreover, the Chinese have experienced not only physical abuse but also cyber violence, such as verbal attacks in their lives(Haynes 2020). Therefore, the racial discrimination generated by the western perspective has not disappeared. Instead, racism has been amplified by the characteristics of the smooth transmission of the Internet. The cyber-world is not like the electronic media theory says: there is no entity in the cyber world, so there is no postcolonial problem. (Fernández 1999)

The racism shown in the "Chinese virus" incident is what postcolonialism criticizes. So I don't think the electronic media theory about that marginality and subalternity exist outside cyberspace is appropriate. There are still problems on the Internet caused by western centrism, racism, and so on. In the past, the description of specific incidents of racial discrimination mainly appeared in literary works and news reports, so the postcolonial theory was applied primarily on literary research. Now, everyone can post their story online. Gathering and analyzing this information on social media may lead to a more realistic postcolonial study(Shome 2016). The research of comments about discrimination from social media is a good starting point to combine postcolonialism with the theory of electronic media. Maybe I will do such research in the future.

Reference
FERNÁNDEZ, M. 1999. Postcolonial Media Theory. Art Journal, 58, 58-73.
HAYNES, S. 2020. As Coronavirus Spreads, So Does Xenophobia and Anti-Asian Racism [Online]. U.S: Time. Available: https://time.com/5797836/coronavirus-racism-stereotypes-attacks/ [Accessed 3/4/2020 2020].
JINGNAN, H., AUBREY, A. & WROTH, C. 2020. Should We All Be Wearing Masks In Public? Health Experts Revisit The Question [Online]. U.S.A: NPR. Available: https://www.npr.org/sections/health-shots/2020/03/31/824560471/should-we-all-be-wearing-masks-in-public-health-experts-revisit-the-question [Accessed 2/4/2020 2020].
LEUNG, H. 2020. Why Wearing a Face Mask Is Encouraged in Asia, but Shunned in the U.S. [Online]. U.S.: Time. Available: https://time.com/5799964/coronavirus-face-mask-asia-us/ [Accessed 2/4/2020 2020].
ROGERS, K., JAKES, L. & SWANSON, A. 2020. Trump Defends Using ‘Chinese Virus’ Label, Ignoring Growing Criticism [Online]. U.S.: The New York Times Company. Available: https://www.nytimes.com/2020/03/18/us/politics/china-virus.html?_ga=2.43349477.1332171321.1585815403-1383123887.1585815403 [Accessed 2/4/2020 2020].
YOUNG, R. J. C. 2001. Postcolonialism: an historical introduction.

**Comment by Karina-Han** [comment]
这篇文章也借助了翻译器，矫正错误的工具，它们并不尽善尽美。
比如最后我的引用， an historical introduction, 不定冠词应该用a就好了，但它就是用了an， 这是一本书名，可能对应后面的introduction.

**Comment by liaodapo** [comment]
D和K的文章同样有趣，
D的文章更贴切“心智”，但K的文章，仔细想想，也没有不心智
D的这次的文章对代码体进行了大力优化，但依然不如K的看起来舒畅——准确的说，是K的文章在腾到翻译软件里的时候更方便
但K的文章有强烈的知识诅咒，
而D的文章也不足500 words
综上所述，对消优劣，D再一次输在了代码体

**Comment by xysjou** [comment]
At first,I read this book,then,I knew the book of The River,and knew her husband of He Wei,and finally I knew than the writer of He Wei’s  wife .

He Wei also wrote villagers in The River, writing about their rustic enthusiasm and kindness to others. And his wife write other villagers，their are girls of eace one 16 years,and come from the mountain.But they live their village for works to Dongguan.AT first,they stay work in different of factory,and work hard ,and soon later,some of them some became clerks, some became salesmen, and some still struggled on the assembly line. Every girl want to change life.So some of one learn English, learn sales, learn lectures ...and adapt to society.I read this book,and at first accept struggling and vigorous, upward vitality, fresh power rising in the land.

**Comment by liaodapo** [comment]
会议录像链接: https://pan.baidu.com/s/1qkeIJBhbNmoHtbkWtzX9tA 提取码: r14u
